# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 18:39
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('nationality', models.CharField(max_length=255)),
                ('current_location', models.CharField(max_length=255)),
                ('work', models.CharField(max_length=255)),
                ('startup_status', models.BooleanField(default=False)),
                ('portfolio_status', models.BooleanField(default=False)),
                ('itc_program_name', models.CharField(
                    choices=[('F', 'Fellows'), ('B', 'CTO Bootcamp'), ('I', 'Internship'), ('E', 'Experience')],
                    default='E', max_length=1)),
                ('itc_program_year', models.IntegerField(default=2010,
                                                         validators=[django.core.validators.MinValueValidator(2013),
                                                                     django.core.validators.MaxValueValidator(2016)])),
                ('linked_in_url', models.CharField(max_length=255)),
                ('skills', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.',
                                                           through='taggit.TaggedItem', to='taggit.Tag',
                                                           verbose_name='Tags')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
