# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='additional_language',
            field=models.CharField(
                choices=[(b'en', b'English'), (b'es', b'Spanish'), (b'fr', b'French'), (b'he', b'Hebrew')],
                max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_language',
            field=models.CharField(
                choices=[(b'en', b'English'), (b'es', b'Spanish'), (b'fr', b'French'), (b'he', b'Hebrew')],
                default='en', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_language',
            field=models.CharField(
                choices=[(b'en', b'English'), (b'es', b'Spanish'), (b'fr', b'French'), (b'he', b'Hebrew')],
                max_length=12, null=True),
        ),
    ]
