# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 21:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20160128_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alumni',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='itc_program_cohort',
            field=models.CharField(
                choices=[(b'Jan', b'Jan'), (b'Feb', b'Feb'), (b'Mar', b'Mar'), (b'Apr', b'Apr'), (b'May', b'May'),
                         (b'Jun', b'Jun'), (b'Jul', b'Jul'), (b'Aug', b'Aug'), (b'Sep', b'Sep'), (b'Oct', b'Oct'),
                         (b'Nov', b'Nov'), (b'Dec', b'Dec')], default='Jan', max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='itc_program_name',
            field=models.CharField(
                choices=[('F', 'Fellows'), ('B', 'CTO Bootcamp'), ('I', 'Interns'), ('E', 'Experience')], default='E',
                max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='itc_program_year',
            field=models.IntegerField(default=2013, validators=[django.core.validators.MinValueValidator(2013),
                                                                django.core.validators.MaxValueValidator(2016)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linked_in_url',
            field=models.CharField(default='http://linkedin.com/', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
