# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160128_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cluster',
            field=models.IntegerField(default=0),
        ),
    ]
