# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 18:50
from __future__ import unicode_literals

import datetime

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('urgent', models.BooleanField(default=False)),
                ('location',
                 models.CharField(choices=[('S', 'Skype'), ('F', 'Face To Face'), ('I', 'Indifferent')], default='F',
                                  max_length=1)),
                ('date_start', models.DateField(default=datetime.datetime(2016, 1, 28, 20, 50, 51, 397000))),
                ('date_end', models.DateField(default=datetime.datetime(2016, 1, 28, 20, 50, 51, 397000))),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro',
                                               to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req',
                                                to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'Help Request',
                'verbose_name_plural': 'Help Requests',
            },
        ),
    ]
