# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 19:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='interview_prep_choices',
            field=models.CharField(blank=True, choices=[('T', 'Technical'), ('H', 'HR')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='mentoring_choices',
            field=models.CharField(blank=True, choices=[('T', 'Technical'), ('B', 'Business')], max_length=1,
                                   null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='type',
            field=models.CharField(choices=[('M', 'Mentoring'), ('P', 'Interview Prep')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='date_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
